# This is a workflow for Unit, Integration, and Regression Tests

name: CI

on:
  push:
    - branches: [ main ]
    - paths: '**.py'
  pull_request:
    - branches: [ main ]
    - paths: '**.py'
  workflow_dispatch:

jobs:
  unit_and_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python-poetry-env
      - name: Downloading test data
        run: |
          make get_test_data
      - name: Running tests
        run: poetry run coverage run --source=jwave -m pytest -xvs --ignore=tests/regression_tests
      - name: "Upload coverage data for unit and integration tests"
        uses: actions/upload-artifact@v2
        with:
          name: coverage-unit
          path: ./.coverage

  regression_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python-poetry-env
      - name: Downloading test data
        run: |
          make get_test_data
      - name: Running tests
        run: poetry run coverage run --source=jwave -m pytest -xvs ./tests/regression_tests
      - name: "Upload coverage data for regression tests"
        uses: actions/upload-artifact@v2
        with:
          name: coverage-regression
          path: ./.coverage

  combine_coverage:
    needs: [unit_and_integration_tests, regression_tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install coverage
        run: pip install coverage
      - name: Download coverage data
        uses: actions/download-artifact@v2
        with:
          name: coverage-unit
          path: unit
      - name: Download coverage data
        uses: actions/download-artifact@v2
        with:
          name: coverage-regression
          path: regression
      - name: Combine coverage data
        run: |
          mv unit/.coverage .coverage.unit
          mv regression/.coverage .coverage.regression
          coverage combine
          coverage xml
      - name: "Upload combined coverage to Codecov"
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          name: codecov-umbrella
